import { Link } from "react-router-dom";
import { FiArrowRight } from "react-icons/fi";
import SiteHeader from "../Components/SiteHeader";
import { usePageTitle } from "../hooks/usePageTitle";

const metrics = [
  {
    name: "Class Pulse",
    tagline: "0–100 readiness score",
    description:
      "A single number that tells you whether your class is ready to move on. It blends three signals: how accurately students answered (60%), how well their confidence matched their performance (25%), and a small penalty for statistical outliers who may be distorting the average (15%). A score above 75 means you're clear to advance. Below 50 means core concepts need reteaching.",
    how: "Computed entirely on the client from quiz submission data — no AI required.",
    color: "bg-blue-50 border-blue-200",
    label: "bg-blue-600",
  },
  {
    name: "Confidence Calibration",
    tagline: "Are students accurate about their own knowledge?",
    description:
      "After each question, students rate their confidence on a 1–5 scale. PulseCheck compares that rating to whether they actually got the answer right. A well-calibrated student knows what they know. A student who is highly confident but frequently wrong is the most dangerous gap — they won't seek help because they don't think they need it.",
    how: "Calculated per student as the difference between their average confidence score and their actual accuracy.",
    color: "bg-amber-50 border-amber-200",
    label: "bg-amber-500",
  },
  {
    name: "Question Accuracy",
    tagline: "Which questions tripped up the class?",
    description:
      "For each question, PulseCheck shows the percentage of students who answered correctly. Color-coded green (≥70%), yellow (40–69%), or red (<40%) so you can spot problem areas instantly without reading a table of numbers.",
    how: "Straight percentage: correct answers ÷ total submissions for that question.",
    color: "bg-emerald-50 border-emerald-200",
    label: "bg-emerald-600",
  },
  {
    name: "AI Student Action Plans",
    tagline: "A specific next step for every student",
    description:
      "When you click 'Analyze with AI', PulseCheck sends your anonymized quiz data to Google Gemini. It returns a personalized plan for each student: the specific misconceptions behind their wrong answers, an opening line you can say to them, and a risk level (high / medium / low) based on their score and calibration pattern.",
    how: "Generated by Gemini 2.5 Flash using only wrong answer data and confidence scores — no personal information is sent.",
    color: "bg-violet-50 border-violet-200",
    label: "bg-violet-600",
  },
  {
    name: "Study Guide",
    tagline: "Shareable review material, generated from your class's mistakes",
    description:
      "Also generated by Gemini, the study guide is built around the concepts your class struggled with most. Each section explains why a topic matters and gives concrete practice tips. You can share it with students via a public link — they don't need an account to view it.",
    how: "Gemini generates the guide from question accuracy data and the most common wrong answers. Stored in Firestore and accessible via a public URL.",
    color: "bg-teal-50 border-teal-200",
    label: "bg-teal-600",
  },
  {
    name: "Distractor Analysis",
    tagline: "Why did wrong answers happen?",
    description:
      "For every question, AI explains which wrong answer was most popular, what misconception it reveals, and what teaching move addresses it. This is the difference between knowing a student was wrong and knowing why — which is what actually lets you fix it.",
    how: "Per-question AI analysis generated alongside student action plans in the same Gemini call.",
    color: "bg-rose-50 border-rose-200",
    label: "bg-rose-600",
  },
];

export default function AboutPage() {
  usePageTitle("About");
  return (
    <div className="min-h-screen bg-white font-sans text-gray-900">

      {/* Nav */}
      <SiteHeader>
        <Link
          to="/signin"
          className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-700"
        >
          Get started <FiArrowRight className="h-3.5 w-3.5" />
        </Link>
      </SiteHeader>

      <div className="mx-auto max-w-3xl px-6 py-16">

        {/* Hero */}
        <div className="mb-14">
          <p className="mb-3 inline-block rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-xs font-medium text-gray-500">
            What is PulseCheck?
          </p>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
            The quiz tool that tells you what to do next.
          </h1>
          <p className="mt-5 text-lg leading-relaxed text-gray-500">
            Teachers give quizzes all the time. The hard part isn't collecting answers — it's figuring out
            what those answers mean and what to do on Monday morning. PulseCheck turns raw quiz results into
            a clear picture of where each student is, which concepts to revisit, and exactly what to say to
            the students who are struggling.
          </p>
          <p className="mt-4 text-lg leading-relaxed text-gray-500">
            It works in three steps: you build a quiz (or let AI generate one from your notes), students
            take it on their phones with no login required, and you instantly see analytics, AI-generated
            insights, and a shareable study guide.
          </p>
        </div>

        {/* How it works */}
        <div className="mb-14">
          <h2 className="mb-6 text-xl font-bold tracking-tight text-gray-900">How it works</h2>
          <div className="space-y-4">
            {[
              { step: "1", title: "Build a quiz", body: "Type your questions manually, or paste in your lesson notes and let Gemini AI generate a multiple-choice quiz for you. Each question gets assigned a concept tag and cognitive level automatically." },
              { step: "2", title: "Share a link", body: "Copy the quiz link and post it in your LMS, Google Classroom, or just paste it in the chat during class. Students open it on any device — no account, no app download." },
              { step: "3", title: "Read the results", body: "As students submit, the dashboard updates in real time. You see question accuracy, a class readiness score, outlier alerts, and per-student confidence calibration. One click generates AI action plans." },
            ].map((item) => (
              <div key={item.step} className="flex gap-4 rounded-lg border border-gray-100 bg-gray-50 p-5">
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-xs font-bold text-white">
                  {item.step}
                </div>
                <div>
                  <p className="font-semibold text-gray-900">{item.title}</p>
                  <p className="mt-1 text-sm leading-relaxed text-gray-500">{item.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Metrics */}
        <div>
          <h2 className="mb-2 text-xl font-bold tracking-tight text-gray-900">How each metric is calculated</h2>
          <p className="mb-8 text-sm text-gray-500">
            Every number in PulseCheck has a specific definition. Here's exactly what you're looking at.
          </p>
          <div className="space-y-4">
            {metrics.map((m) => (
              <div key={m.name} className={`rounded-lg border p-6 ${m.color}`}>
                <div className="flex items-start gap-3">
                  <span className={`mt-0.5 rounded px-2 py-0.5 text-xs font-semibold text-white ${m.label}`}>
                    {m.name}
                  </span>
                  <span className="text-sm text-gray-500">{m.tagline}</span>
                </div>
                <p className="mt-3 text-sm leading-relaxed text-gray-700">{m.description}</p>
                <p className="mt-3 rounded bg-white/60 px-3 py-2 text-xs text-gray-500">
                  <span className="font-semibold text-gray-600">How it's generated: </span>{m.how}
                </p>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="mt-16 rounded-xl border border-gray-200 bg-gray-50 p-8 text-center">
          <h2 className="text-xl font-bold text-gray-900">Ready to try it?</h2>
          <p className="mt-2 text-sm text-gray-500">Create a quiz in under two minutes. Free, no credit card.</p>
          <Link
            to="/signin"
            className="mt-5 inline-flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-semibold text-white transition-colors hover:bg-blue-700"
          >
            Get started <FiArrowRight />
          </Link>
        </div>

      </div>
    </div>
  );
}
